# Generated by Django 5.1.7 on 2025-04-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField(blank=True, max_length=3, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('chaptername', models.CharField(blank=True, max_length=20, null=True)),
                ('notesFile', models.FileField(upload_to='notes/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('presentDays', models.IntegerField(max_length=5)),
                ('absentDays', models.IntegerField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('totalFees', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('paidFees', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('dueFees', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('testDate', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=15, null=True)),
                ('totalMarks', models.IntegerField(blank=True, max_length=4, null=True)),
                ('scoredMarks', models.IntegerField(blank=True, max_length=4, null=True)),
                ('percentage', models.IntegerField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
