# Generated by Django 5.2.3 on 2025-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_events_notes_attendance_fees_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaultFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField(max_length=2)),
                ('defaultFees', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
