# Generated by Django 5.2.3 on 2025-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_defaultfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absentDays',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='presentDays',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
