# Generated by Django 5.2.3 on 2025-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attendance_absentdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='scoredMarks',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='totalMarks',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
