# Generated by Django 5.2.3 on 2025-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_marks_percentage_alter_marks_scoredmarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='url',
            new_name='notesUrl',
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
