# Generated by Django 5.2.3 on 2025-06-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_url_notes_notesurl_alter_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='chaptername',
            new_name='chapter',
        ),
    ]
